### ISSUE TITLE
Issue with Non-ASCII character in labelimage.py

### ISSUE THREAD

**Issue by lguerard** [imcf/python-imcflibs#19]
When importing the `labelimage` methods, Fiji returns a `SyntaxError: Non-ASCII character in file '__pyclasspath__/imcflibs/imagej/labelimage.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details` 

Should be fixed for next release.

**Comment by ehrenfeu** [comment]
This should be fixed by the commit above. Will close the issue, please re-open in case you're still seeing this.
