### ISSUE TITLE
Issue with leftovers from previous versions

### ISSUE THREAD

**Issue by lguerard** [imcf/python-imcflibs#20]
The projection type is never referenced in the function and should be cleaned

https://github.com/imcf/python-imcflibs/blob/6d2efdc9ae944d8e9c4f4b1863cadb89e14f9b1b/src/imcflibs/imagej/omerotools.py#L58

**Comment by ehrenfeu** [comment]
From looking at git blame, this was added by @rohangirishrao - maybe you could have a look?

**Comment by rohangirishrao** [comment]
Yup, copy that. Will review!

**Comment by rohangirishrao** [comment]
Sorry, did not mean to close the issue. Github defaults to closing when I make a comment? Interesting...

**Comment by rohangirishrao** [comment]
Seems like the `project_string` has been removed in the latest commit anyway. Thanks for removing that @lguerard, is there anything left to do?
